apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openhab.fullname" . }}
  labels:
    {{- include "openhab.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "openhab.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "openhab.name" . }}  
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "openhab.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openhab.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{- if and .Values.git_config.enabled .Values.git_config.secret_name }}
        - name: git-secret
          secretName: {{ .Values.git_config.secret_name }}
          defaultMode: 0400
      {{- end }}
      {{- if not .Values.persistence.enabled }}
        - name: userdata
          emptyDir: {}
      {{- end }}
      {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: userdata
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
      {{- end }}

      {{- if .Values.git_config.enabled }}
      initContainers:
        - name: openhab-config
          image: k8s.gcr.io/git-sync:v3.1.5
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          - name: git-secret
            mountPath: /etc/git-secret
          env:
            - name: GIT_SYNC_REPO
              value: "git@github.com:kilip/olympus-openhab.git"
            - name: GIT_SYNC_BRANCH
              value: "master"
            - name: GIT_SYNC_DEPTH
              value: "1"
            - name: GIT_SYNC_ROOT
              value: /config
            - name: GIT_SYNC_DEST
              value: openhab
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_KNOWN_HOSTS
              value: "false"
            - name: GIT_SYNC_PERMISSION
              value: "0775"
            - name: GIT_SYNC_SUBMODULES
              value: "off"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
          securityContext:
            runAsUser: 0
      {{- end }}

      # main container
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: ssh
              containerPort: 8101
              protocol: TCP
            - name: lsp
              containerPort: 5007
              protocol: TCP
          volumeMounts:
            - name: userdata
              mountPath: /openhab/userdata
            - name: config
              mountPath: /openhab/conf
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  - metadata:
      name: data
      labels:
        app.kubernetes.io/name: {{ include "openhab.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.persistence.annotations }}
      annotations:
    {{ toYaml .Values.persistence.annotations | indent 4 }}
    {{- end }}
    spec:
      accessModes: [ {{ .Values.persistence.accessMode | quote }} ]
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: {{ .Values.persistence.storageClass | quote }}
    {{- end }}
    {{- end }}
  {{- end }}
