apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
{{- if not .Values.customConfig }}
    {{- if .Values.persistence.enabled }}
    persistence true
    persistence_file mosquitto.db
    persistence_location /mosquitto/data
    {{- end }}

    {{- if .Values.passwordEntries }}
    password_file /mosquitto/config/password.conf
    allow_anonymous false
    {{- end }}
    
    listener 1883 0.0.0.0
    listener 8883 0.0.0.0
{{- end }}
{{- if .Values.passwordEntries }}
  password.conf: |
    {{ .Values.passwordEntries }}
{{- end }}
